---

- hosts: nginx
  become: true
  gather_facts: no
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  remote_user: ubuntu
  

  tasks:
    - name: nginx
      apt: name=nginx state=latest

    - name: make sure nginx is running
      service: name=nginx state=started

    - name: unitTest - Nginx is running
      command: /bin/systemctl status nginx
      register: result
      changed_when: false
      failed_when: "'Active: active (running)' not in result.stdout"
      tags:
        - unitTests